#include "AEEStdDef.idl"
#include "remote.idl"

interface luminal_hexagon : remote_handle64 {
    AEEResult compute(in uint32 op, in uint32 n, in uint32 m, in uint32 k,
                      in uint32 flags,
                      in sequence<octet> a, in sequence<octet> b,
                      rout sequence<octet> result);
};
