//! Small, deterministic C/HVX source generator used by the SDK DSP target.

/// The operation numbers are part of the FastRPC compute ABI. Do not reorder
/// existing values once a deployed skel uses them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum BinaryOp {
    AddF32 = 0,
    MulF32 = 1,
}

impl BinaryOp {
    pub const fn function_name(self) -> &'static str {
        match self {
            Self::AddF32 => "luminal_add_f32",
            Self::MulF32 => "luminal_mul_f32",
        }
    }

    const fn vector_expression(self) -> &'static str {
        match self {
            Self::AddF32 => "Q6_Vsf_equals_Vqf32(Q6_Vqf32_vadd_VsfVsf(va, vb))",
            Self::MulF32 => "Q6_Vsf_equals_Vqf32(Q6_Vqf32_vmpy_VsfVsf(va, vb))",
        }
    }
}

/// Emit a v73 HVX DSP implementation for the selected binary operations.
///
/// The generated dispatcher has the function signature produced by the
/// matching QAIC interface in `device/luminal_hexagon.idl`. Inputs and output
/// are byte buffers because the ABI is intentionally dtype/layout-neutral;
/// this first backend slice validates F32 contiguous tensors before dispatch.
pub fn emit_dsp_source(ops: &[BinaryOp]) -> String {
    let mut unique = Vec::new();
    for &op in ops {
        if !unique.contains(&op) {
            unique.push(op);
        }
    }

    let mut source = String::from(
        r#"/* Generated by luminal_hexagon::codegen. */
#include <AEEStdDef.h>
#include <stdint.h>
#include <stddef.h>
#include <hexagon_types.h>
#include <hvx_hexagon_protos.h>
#include "luminal_hexagon.h"

enum {
    LUMINAL_HEXAGON_ADD_F32 = 0,
    LUMINAL_HEXAGON_MUL_F32 = 1,
};

static inline void luminal_copy_tail(float *out, const float *a, const float *b,
                                     uint32_t begin, uint32_t n, int multiply) {
    for (uint32_t i = begin; i < n; ++i) {
        out[i] = multiply ? a[i] * b[i] : a[i] + b[i];
    }
}

"#,
    );

    for op in &unique {
        source.push_str(&format!(
            r#"static void {name}(const float *a, const float *b, float *out, uint32_t n) {{
    const uint32_t vectors = n & ~31u; /* 128-byte HVX vector / 4-byte F32 */
    for (uint32_t i = 0; i < vectors; i += 32) {{
        const HVX_Vector va = *(const HVX_UVector *)(a + i);
        const HVX_Vector vb = *(const HVX_UVector *)(b + i);
        const HVX_Vector vc = {expression};
        *(HVX_UVector *)(out + i) = vc;
    }}
    luminal_copy_tail(out, a, b, vectors, n, {multiply});
}}

"#,
            name = op.function_name(),
            expression = op.vector_expression(),
            multiply = u8::from(*op == BinaryOp::MulF32),
        ));
    }

    source.push_str(
        r#"AEEResult luminal_hexagon_open(const char *uri, remote_handle64 *handle) {
    (void)uri;
    *handle = 1;
    return AEE_SUCCESS;
}

AEEResult luminal_hexagon_close(remote_handle64 handle) {
    (void)handle;
    return AEE_SUCCESS;
}

AEEResult luminal_hexagon_compute(remote_handle64 handle, uint32_t op, uint32_t n,
                                  const unsigned char *a, int a_len,
                                  const unsigned char *b, int b_len,
                                  unsigned char *out, int out_len) {
    (void)handle;
    if (!a || !b || !out || a_len < 0 || b_len < 0 || out_len < 0 ||
        (uint64_t)n * sizeof(float) > (uint64_t)a_len ||
        (uint64_t)n * sizeof(float) > (uint64_t)b_len ||
        (uint64_t)n * sizeof(float) > (uint64_t)out_len) {
        return AEE_EBADPARM;
    }
    switch (op) {
"#,
    );

    for op in &unique {
        source.push_str(&format!(
            "        case {value}: {name}((const float *)a, (const float *)b, (float *)out, n); break;\n",
            value = *op as u32,
            name = op.function_name(),
        ));
    }
    source.push_str(
        r#"        default: return AEE_EUNSUPPORTED;
    }
    return AEE_SUCCESS;
}
"#,
    );
    source
}

/// SDK compiler settings for the Snapdragon X Elite's Hexagon v73 HVX unit.
pub const V73_CFLAGS: &[&str] = &["-mv73", "-mhvx", "-mhvx-length=128B"];
